{% set name = "cuiman" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cuiman-{{ version }}.tar.gz
  sha256: 1e67f0fde9bb6217db0757a478ab623e8be04f19a77c264d7047e5c01d312be2

build:
  entry_points:
    - cuiman = cuiman.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - click
    - panel
    - pydantic
    - pydantic-settings
    - pyyaml
    - typer
    - uri-template
    - httpx
    - gavicore >=0.0.9

test:
  imports:
    - cuiman
  commands:
    - pip check
    - cuiman --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/eo-tools/eozilla/tree/main/cuiman
  doc_url: https://eo-tools.github.io/eozilla/
  dev_url: https://github.com/eo-tools/eozilla/
  summary: A client for the OGC API - Processes, Part 1.
  description: |
    Eozilla 🦖 Cuiman is a package tha provides a client Python API, GUI, and CLI 
    for servers compliant with the OGC API - Processes, Part 1.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AliceBalfanz
    - b-yogesh
    - clarasb
    - forman
    - konstntokas
    - pont-us
    - TejasMorbagal
    - thomasstorm
    - TonioF
